// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApYqVm0Re3DyfKgj30fZ5OoxoFV5dL6VE',
    appId: '1:1055094454445:web:40a979da643395b218ae24',
    messagingSenderId: '1055094454445',
    projectId: 'foxxy-acf46',
    authDomain: 'foxxy-acf46.firebaseapp.com',
    storageBucket: 'foxxy-acf46.appspot.com',
    measurementId: 'G-QGQ5MCW9K9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI3Hd2fh_0xk4_SuWDPoHjaI9s8CR7PfE',
    appId: '1:1055094454445:android:6d5995c74c6d9a2318ae24',
    messagingSenderId: '1055094454445',
    projectId: 'foxxy-acf46',
    storageBucket: 'foxxy-acf46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR25-JidYnx-XekHz8xIc_H0o5PR1PKHc',
    appId: '1:1055094454445:ios:3fd6a42b7976830a18ae24',
    messagingSenderId: '1055094454445',
    projectId: 'foxxy-acf46',
    storageBucket: 'foxxy-acf46.appspot.com',
    iosClientId: '1055094454445-sosk9rpnpaj1f747e8l58bn00dlosfs0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR25-JidYnx-XekHz8xIc_H0o5PR1PKHc',
    appId: '1:1055094454445:ios:15c9fb938ac160ba18ae24',
    messagingSenderId: '1055094454445',
    projectId: 'foxxy-acf46',
    storageBucket: 'foxxy-acf46.appspot.com',
    iosClientId: '1055094454445-sk58hdufvbeib3bhtbic31d02d3b57ft.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatting.RunnerTests',
  );
}
